server:
  port: 9090

##   Mysql DataBase configuration
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false
  datasource:
    url: jdbc:mysql://localhost:3306/linkdinDataModel
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE



# H2 DataBase configuration
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: true
#        web-allow-others: false
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create

